source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'AIImageResize_Example' do
  pod 'AIImageResize', :path => '../'

  target 'AIImageResize_Tests' do
    inherit! :search_paths
  end
end
